### ISSUE TITLE
cannot find or generate TIMIT_labels.npy

### ISSUE THREAD

**Issue by Jason-1998** [smallflyingpig/learning-to-fool-the-speaker-recognition#1]
Traceback (most recent call last):
  File "train_transformer.py", line 659, in <module>
    main(args)
  File "train_transformer.py", line 588, in main
    train_dataset = TIMIT_speaker(args.data_root, train=True, phoneme=True, norm_factor=True)
  File "/data/gjj/fool/learning-to-fool-the-speaker-recognition/dataset.py", line 66, in __init__
    self.timit_labels = np.load(os.path.join(data_root_processed, "TIMIT_labels.npy")).item()
  File "/home/gjj/anaconda3/envs/torch/lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/gjj/fool/learning-to-fool-the-speaker-recognition/data/TIMIT/TIMIT_lower/processed/TIMIT_labels.npy'

hello,
when I try to train the model, I meet this error. I don't have this npy file.
But I went through the data_prepare file, I also cannot find how to generate this file.
Is there something you missed in the README?Or how can I get or generate this file.
Thank you.

**Comment by surajbhondave** [comment]
@Jason-1998 were u able to load the dataset. if so kindly help me
